version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: hedgedoc
      POSTGRES_USER: hedgedoc
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./data/db:/var/lib/postgresql/data

  hedgedoc:
    image: quay.io/hedgedoc/hedgedoc:1.9.9
    restart: always
    depends_on:
      - db
    environment:
      # Domain & Protocol
      CMD_DOMAIN: notes.sotcpu.me
      CMD_PROTOCOL_USESSL: "true"
      CMD_URL_ADDPORT: "false"

      # DB config
      CMD_DB_URL: postgres://hedgedoc:db_password@db:5432/hedgedoc

      # Authentication
      CMD_ALLOW_EMAIL_LOGIN: "true"
      CMD_ALLOW_REGISTER: "true"

      # Session
      CMD_SESSION_SECRET: ""

      # Other optional configs
      CMD_ALLOW_ANONYMOUS: "true"
      CMD_IMAGE_UPLOAD_TYPE: "filesystem"
      CMD_HSTS_ENABLE: "true"

    ports:
      - "3000:3000" # for internal use, nginx reverse proxy this
    volumes:
      - ./uploads:/hedgedoc/public/uploads
